[
	{
	 "id": "0",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_shingeki-no-kyojin.jpg",
	 "title": "Attack On Titan",
	 "seasons": 4,
	 "series": 87,
	 "films": 2,
	 "description": "The plot of Attack on Titan centers on a civilization inside three walls. According to the knowledge propagated locally, it is the last location where humans still live. Its inhabitants have been led to believe that over one hundred years ago, humanity was driven to the brink of extinction after the emergence of humanoid giants called Titans, who attack and eat humans on sight. The last remnants of humanity retreated behind three concentric walls and enjoyed nearly a century of peace. Within the walls, the thought of venturing outside is strongly frowned upon and discouraged. To combat Titans, the country's military employs Vertical Maneuvering Equipment, a set of waist-mounted grappling hooks and gas-powered propulsion enabling immense mobility in three dimensions.",
	 "src": "https://r80108.kujo-jotaro.com/shingeki-no-kyojin/1/1.480.fab90a900c1f2df9.mp4?hash1=35869f6ed740bb6757f6629c6187f6ee&hash2=1da54cdf60d8ae7a74261e6f67761e5e",
	 "poster": "https://s5o.ru/storage/simple/cyber/edt/d7/0c/f2/f4/cybere49ec3e20f7.jpg",
	 "category": 1,
	 "rating": 10
	},
	{
	 "id": "1",
	 "imageUrl": "https://gen.jut.su/templates/school/images/anime_naruto_season-1.jpg",
	 "title": "Naruto",
	 "seasons": 3,
	 "series": 980,
	 "films": 11,
	 "description": "Naruto is a ninja-in-training whose wild antics amuse his teammates. But he's completely serious about one thing: becoming the world's greatest ninja! As the battle against the Tailed Beast-targeting Akatsuki rages on, the heroic sibling battle between Sasuke and Itachi eventually concludes. Though Sasuke has achieved his lifelong goal, Madara reveals Itachi's real motivations. With the truth uncovered, Sasuke sets out to destroy Konoha!",
	 "src": "https://r360104.kujo-jotaro.com/naruto/2/1.360.9277a1180f505f46.mp4?hash1=7711ac87762b16dd1626bed81fa4fdb2&hash2=0bd638b82f392c16271aed825652ea48",
	 "poster": "/img/3.jpg",
	 "category": 2,
	 "rating": 9
	},
	{
	 "id": "2",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_hunter-x-hunter.jpg",
	 "title": "Huter X Hunter",
	 "seasons": 1,
	 "series": 148,
	 "films": 1,
	 "description": "The story focuses on a young boy named Gon Freecss who discovers that his father, who left him at a young age, is actually a world-renowned Hunter, a licensed professional who specializes in fantastical pursuits such as locating rare or unidentified animal species, treasure hunting, surveying unexplored enclaves",
	 "src": "https://r80108.kujo-jotaro.com/hunter-x-hunter/1.480.c41c0120f90ad833.mp4?hash1=9338b8b1d222fd33f86ad3bb32a69798&hash2=fb83d8f68260539220d3044bd38e5d51",
	 "poster": "https://wallpaper.dog/large/20476144.jpg",
	 "category": 3,
	 "rating": 8
	},
	{
	 "id": "3",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_code-geass.jpg",
	 "title": "Code Geass",
	 "seasons": 2,
	 "series": 50,
	 "films": 6,
	 "description": "In an alternative timeline, the world is divided into three superpowers (similar to the world of Nineteen Eighty-Four by George Orwell): the Holy Britannian Empire (the Americas; also called Britannia), the Chinese Federation (Asia), and the Europa United (Europe and Africa). The story takes place after the Holy Britannian Empire's conquest of Japan on August 10, 2010 a.t.b., by means of Britannia's newest weapon, the Autonomous Armored Knight, or Knightmare Frame. In turn, Britannia effectively strips Japan and its citizens of all rights and freedoms and renames the country Area 11 with its citizens referred to as Elevens.",
	 "src": "https://r80108.kujo-jotaro.com/code-geass/1/1.480.7d03d247724d6a46.mp4?hash1=5ab695b70f74a8f4672d1e625864e512&hash2=561b52f6aa7f105c67f68946a2137378",
	 "poster": "https://wallpaperset.com/w/full/d/c/a/480785.jpg",
	 "category": 4,
	 "rating": 7
	},
	{
	 "id": "4",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_fullmetal-alchemist.jpg",
	 "title": "Fullmetal Alchemist",
	 "seasons": 2,
	 "series": 115,
	 "films": 2,
	 "description": "Fullmetal Alchemist takes place in the fictional country of Amestris (アメストリス, Amesutorisu). In this world, alchemy is one of the most-practiced sciences; alchemists who work for the government are known as State Alchemists (国家錬金術師, Kokka Renkinjutsushi) and are automatically given the rank of major in the military. Alchemists have the ability, with the help of patterns called transmutation circles, to create almost anything they desire. However, when they do so, they must provide something of equal value in accordance with the Law of Equivalent Exchange.",
	 "src": "https://r310.kujo-jotaro.com/fullmetal-alchemist/1/1.480.57e3a16b1201ebe7.mp4?hash1=f27a5f3fc79144cb5a7597bb475dd4a7&hash2=a268ceb538564f899f89d7bc14aeadc7",
	 "poster": "https://m.media-amazon.com/images/I/61H-J4CFoVL._SL1024_.jpg",
	 "category": 5,
	 "rating": 6
	},
	{
	 "id": "5",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_haikyuu.jpg",
	 "title": "Volleyball",
	 "seasons": 4,
	 "series": 85,
	 "films": 2,
	 "description": "In November 2019, Polygon named Haikyu!! one of the best anime of the 2010s,[76] and Crunchyroll listed it in their Top 100 best anime of the 2010s.[77] IGN also listed Haikyu!! among the best anime series of the 2010s,[78] and nominated it for Best Anime Series of 2016.[79] According to Crunchyroll, Haikyu!! was one of the top 10 streamed anime in the UK, Canada, Oceania, Mexico, and Brazil on their streaming service during the winter 2020 anime season.[80] On Tumblr's 2020 Year in Review, which highlights the largest communities, fandoms, and trends on the platform throughout the year, Haikyu!! ranked 2nd on the Top Anime & Manga Shows category, only behind My Hero Academia.[81]",
	 "src": "https://r80108.kujo-jotaro.com/haikyuu/1/1.480.ce7ebcc1387ddc4e.mp4?hash1=0b044ceda7edc39d0ee7428086492e32&hash2=e6e4d3810112ddd3743ba7c7b60b07eb",
	 "poster": "https://www.animerankers.com/wp-content/uploads/2020/09/Best-volleyball-anime.jpg",
	 "category": 1,
	 "rating": 5
	},
	{
	 "id": "6",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_one-punch-man.jpg",
	 "title": "One Punch Man",
	 "seasons": 2,
	 "series": 24,
	 "films": 1,
	 "description": "Who the fuck got the streets hot? Lil' bro spent all his money on a cheap Glock Nigga got some stanking ass socks, got your feet hot Nigga died for a cheap watch, that's a G-SHOCK I just put a drum on my—, yeah, that's a beatbox I broke into bitch crib? I had to sneak out",
	 "src": "https://r80108.kujo-jotaro.com/one-punch-man/1.480.e749636525190b95.mp4?hash1=2b3b2e0b453b8f15e8c931e814ce32e6&hash2=4523b28febe9b8593bc9ff0482c64932",
	 "poster": "https://www.xtrafondos.com/wallpapers/saitama-one-punch-man-3213.jpg",
	 "category": 2,
	 "rating": 4
	},
	{
	 "id": "7",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_kimetsu-no-yaiba.jpg",
	 "title": "Demon Slayer",
	 "seasons": 3,
	 "series": 44,
	 "films": 1,
	 "description": "The story takes place in Taishō-era Japan, where a secret society, known as the Demon Slayer Corps, has been waging a secret war against demons for centuries. The demons are former humans who were turned into demons by Muzan Kibutsuji injecting them with his own blood, and they feed on humans and possess supernatural abilities such as super strength, powers that demons can obtain called Blood Demon Art",
	 "src": "https://r80108.kujo-jotaro.com/kimetsu-no-yaiba/1.480.c81ba9cc95926096.mp4?hash1=ca3ef5e4d15866e43e952749ff3c7df7&hash2=ef8e0c28b5c73ff597b91d45acbc69af",
	 "poster": "https://i.pinimg.com/originals/b3/ff/1c/b3ff1c5e22c2a008b82417d9606a8413.png",
	 "category": 3,
	 "rating": 3
	},
	{
	 "id": "8",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_berserk.jpg",
	 "title": "Berserk",
	 "seasons": 3,
	 "series": 49,
	 "films": 3,
	 "description": "Guts is a lone mercenary warrior who wanders looking for battles, driven solely by his will to survive. After being defeated by Griffith, the ambitious and charismatic leader of a mercenary group called the Band of the Hawk, Guts becomes a full member of the group. Guts quickly rises through the ranks, becoming Griffith's best warrior. One day, Griffith shows Guts his Behelit, a mysterious demonic relic, revealing him as well his dream to rule a kingdom of his own. Three years later, the Band of the Hawk have grown in power and numbers, with Guts serving as a commander of the group. Guts encounters Immortal Zodd, a fearsome giant warrior, who after nearly killing him and Griffith, spares their lives upon seeing Griffith's Behelit, warning Guts of an inescapable death should Griffith's dream die. ",
	 "src": "https://r100208.kujo-jotaro.com/berserk/1/1.480.fbb8808a9377d021.mp4?hash1=1d92b28a2e310c93e04c6effb2ad695b&hash2=4cba74a51873c43f78f76992e82fcd7b",
	 "poster": "https://i.pinimg.com/originals/41/12/71/4112718fd4db39e6c4322674e62b6221.jpg",
	 "category": 4,
	 "rating": 9
	},
	{
	 "id": "9",
	 "imageUrl": "https://gen.jut.su/uploads/animethumbs/anime_death-note.jpg",
	 "title": "Death Note ",
	 "seasons": 1,
	 "series": 37,
	 "films": 2,
	 "src": "https://r80108.kujo-jotaro.com/death-note/1.480.b9415bf64b43e619.mp4?hash1=9c48008a63044b67d6cde2439d22a684&hash2=98c87db5c96df82f005b51d8e5213af8",
	 "poster": "https://www.speedtest.pl/wiadomosci/wp-content/uploads/2017/08/deathnote-1280-1490294885083_1280w-1068x601.jpg",
	 "category": 5,
	 "description": "In Tokyo, a disaffected high school student named Light Yagami finds the Death Note, a mysterious black notebook that can kill anyone as long as the user knows both the target's name and face. Initially terrified of its god-like power, Light considers the possibilities of the Death Note's abilities and kills high-profile Japanese criminals, then targets international criminals. Five days after discovering the notebook, Light is visited by Ryuk, a Shinigami and the Death Notes previous owner. Ryuk, invisible to anyone who has not touched the notebook, reveals that he dropped the notebook into the human world out of boredom and is amused by Light's actions",
	 "rating": 8
	}
]